name: "Build"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./github/workflows/actions/install-dependencies
      - run: npm test
      - run: npm run build
