name: "Build"

on:
  workflow_distpath:
  workflow_call:

build:
  runs-on: ubuntu-latest
  steps:
    - uses: ./github/workflows/install-dependencies.yml
    - run: npm test
    - run: npm run build
