name: Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Bump version and push tag
        id: calc_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: "true"
      - run: echo ${{ steps.calc_version.outputs.new_version }}
      - name: Update version
        run: |
          echo package.json
          jq '.version="${{steps.calc_version.outputs.new_version }}"' package.json > package.json
          echo package.json
      - run: git status
      - name: Commit files
        run: |
          git config --local user.email "github-actions-bot@noreply.github.com"
          git config --local user.name "github-actions-bot"
          git commit -m "update package.json to ${{steps.tag_version.outputs.new_version}}" -a

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
  #  - name: Commit files
  #       run: |
  #           git config --local user.email "github-actions-bot@noreply.github.com"
  #           git config --local user.name "github-actions-bot"
  #           git commit -m "update package.json to ${{steps.tag_version.outputs.new_version}} changes" -a
  #       - name: Push changes
  #         uses: ad-m/github-push-action@master
  #         with:
  #           github_token: ${{ secrets.GITHUB_TOKEN }}
  #           branch: ${{ github.ref }}
#
